# Generated by Django 4.0.6 on 2022-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=1000)),
                ('postal_code', models.BigIntegerField(max_length=12)),
                ('address_name', models.CharField(max_length=1000)),
                ('address_line1', models.CharField(max_length=1000)),
                ('address_line2', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('landmark', models.CharField(max_length=1000)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
