# Generated by Django 4.1 on 2022-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cocktail_drinks_garnier_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='garnier',
            name='mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='subs',
            name='mass',
            field=models.IntegerField(),
        ),
    ]
